Updated the AmountBorrowed event
sublime-finance/sublime-v1 pull request #135
Opened 2021-11-16 10:07 UTC by saxenism

Updated the `AmountBorrowed` event (https://github.com/sublime-finance/sublime-v1/blob/update-borrow-event/contracts/Pool/Pool.sol#L342) to have an extra parameter of `_protocolFee`.

2021-11-17 06:23 UTC, prateekreddy requested changes

2021-11-17 06:23 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        emit AmountBorrowed(_tokensLent, _protocolFee);
let's use _tokensLent.sub(_protocolFee) as the first arg

2021-11-17 08:15 UTC, saxenism commented on contracts/Pool/Pool.sol
> +        emit AmountBorrowed(_tokensLent, _protocolFee);
Yeah, that makes more sense. Will update.

2021-11-17 10:15 UTC, prateekreddy requested changes

2021-11-17 10:15 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        emit AmountBorrowed(_tokensLent.sub(_protocolFee), _protocolFee);
Lets not do the sub 2 times, we already do that above right, instead may be we can assign to a memory variable and reuse.

2021-12-08 15:05 UTC, prateekreddy approved these changes

2021-12-08 15:05 UTC, merged