Lime 69
sublime-finance/sublime-v1 pull request #160
Opened 2021-12-27 07:56 UTC by saxenism

I've added the require statement to the external function instead of the internal function as stated in the Lime 69 issue. But I was wondering, whether the require statement should have the condition **_maxStrategies > 0** instead of **_maxStrategies != 0** to filter out negative values of _maxStrategies.

2022-01-11 06:18 UTC, saxenism commented
I've added the require statement to the external function instead of the internal function as stated in the Lime 69 issue. But I was wondering, whether the require statement should have the condition **_maxStrategies > 0** instead of **_maxStrategies != 0** to filter out negative values of _maxStrategies.

@prateekreddy @ritik99

2022-01-11 07:32 UTC, prateekreddy commented
> condition _maxStrategies > 0 instead of _maxStrategies != 0 to filter out negative values of _maxStrategies.

Max strategies cannot be negative because it is unsigned integer

2022-01-11 07:34 UTC, prateekreddy requested changes
Instead of moving maxStrategies check, we can remove the require statement in initialize as suggested.

2022-01-12 06:35 UTC, saxenism commented
> Max strategies cannot be negative because it is unsigned integer

Oh lol, yes true.

> Instead of moving maxStrategies check, we can remove the require statement in initialize as suggested.

Yes, agreed. Made the changes. Please review again.

2022-01-17 15:59 UTC, merged