Named return issues resolved
sublime-finance/sublime-v1 pull request #164
Opened 2021-12-27 08:47 UTC by saxenism

2022-01-11 08:06 UTC, prateekreddy commented
Has this style been consistent across all functions ?

2022-01-11 09:42 UTC, prateekreddy requested changes
@saxenism Please check if this style been consistent across all functions ? Let's ensure we use return everywhere even in case of multiple return value

2022-01-12 07:04 UTC, saxenism commented
> @saxenism Please check if this style been consistent across all functions ? Let's ensure we use return everywhere even in case of multiple return value

Understood. Switched the return style. Please review again.

2022-01-17 16:21 UTC, ritik99 reviewed
@saxenism I don't think the styling is still consistent throughout the contracts. Some instances: [1](https://github.com/sublime-finance/sublime-v1/blob/f25860e182e4c9a8fed0332f1cbd4755d68b3af4/contracts/Pool/Pool.sol#L244), [2](https://github.com/sublime-finance/sublime-v1/blob/f25860e182e4c9a8fed0332f1cbd4755d68b3af4/contracts/Pool/Pool.sol#L165). Please recheck all the contracts

2022-01-19 06:14 UTC, saxenism commented
> @saxenism I don't think the styling is still consistent throughout the contracts. Some instances: [1](https://github.com/sublime-finance/sublime-v1/blob/f25860e182e4c9a8fed0332f1cbd4755d68b3af4/contracts/Pool/Pool.sol#L244), [2](https://github.com/sublime-finance/sublime-v1/blob/f25860e182e4c9a8fed0332f1cbd4755d68b3af4/contracts/Pool/Pool.sol#L165). Please recheck all the contracts

Scanned all contracts and made the return style consistent. Please check again.

Few functions that I did not change:
1. [SavingsAccount.withdrawAll](https://github.com/sublime-finance/sublime-v1/blob/master/contracts/SavingsAccount/SavingsAccount.sol#L304)

This is because I did not see the function returning at all. Maybe we can discuss the function's return declaration. 

2. [PoolFactory._deploy](https://github.com/sublime-finance/sublime-v1/blob/master/contracts/Pool/PoolFactory.sol#L404)

This is because I didn't really want to change a function making an assembly call.

3.[ NoYield.emergencyWithdraw](https://github.com/sublime-finance/sublime-v1/blob/master/contracts/yield/NoYield.sol#L78)

This is because the function's logic is to be changed from another PR, and style changes can be made after that.

2022-02-01 07:19 UTC, prateekreddy commented
@saxenism IsavingsAccount has some inconsistency with the format. Can you check ?

2022-02-01 07:20 UTC, prateekreddy commented
In all the interfaces let's name the return values, so it is more clear. We need not do this on actual functions though.

2022-02-01 10:59 UTC, saxenism commented
> @saxenism In all the interfaces let's name the return values, so it is more clear. We need not do this on actual functions though.
> 
> PoolFactory, SavingsAccount, NoYield has inconsistent return patterns. Please check.

Made the required changes, apart from `NoYield.emergencyWithdraw` because that function has yet to be changed.
Please review again.

2022-02-01 12:17 UTC, prateekreddy requested changes

2022-02-01 12:17 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccountUtil.sol
> +        uint256 _sharesReceived;
This can be declared at initialization ?

2022-02-01 12:17 UTC, prateekreddy commented on contracts/interfaces/IPool.sol
> +    function getMarginCallEndTime(address _lender) external returns (uint256 marginCallEndTimeFor_lender);
Inconsistent naming convention

2022-02-01 12:17 UTC, prateekreddy commented on contracts/interfaces/IPriceOracle.sol
> +    function getLatestPrice(address num, address den) external view returns (uint256 priceOfNumInTermsOfDen, uint256 priceDecimals);
(uint256 price, uint256 decimals) should be sufficient ?

2022-02-01 12:17 UTC, prateekreddy commented on contracts/interfaces/IStrategyRegistry.sol
> +    function getStrategies() external view returns (address[] memory strategiesArray);
strategies should be sufficient

2022-02-01 12:17 UTC, prateekreddy commented on contracts/yield/NoYield.sol
> +     * @return _asset: address of the lqiudity token for the asset
return value and param have same var name

2022-02-03 05:54 UTC, prateekreddy requested changes

2022-02-03 05:54 UTC, prateekreddy commented on contracts/yield/NoYield.sol
> +        address _tokenAddress = _asset;
you can return asset directly, assigning to tokenAddress is not necessary

2022-02-04 04:56 UTC, prateekreddy approved these changes

2022-02-04 04:56 UTC, merged