Storing 30 as a constant
sublime-finance/sublime-v1 pull request #168
Opened 2021-12-27 10:17 UTC by saxenism

2021-12-28 21:59 UTC, saxenism commented
For some reason, line 119 in `contracts/PriceOracle.sol` (check *Evading the error* commit) using the SCALING_FACTOR (1e30) constant always threw an overflow error.

2022-01-11 08:39 UTC, prateekreddy requested changes

2022-01-11 08:39 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +    uint256 constant SCALING_FACTOR = 1e30;
This need not be declared as we aren't using the variable anywhere

2022-01-11 08:39 UTC, prateekreddy commented on contracts/PriceOracle.sol
> +        return (price, SCALING_FACTOR);
30 shouldn't be replaced by 1e30

2022-01-11 08:39 UTC, prateekreddy commented on contracts/PriceOracle.sol
> +        return (_numTokens, SCALING_FACTOR);
30 shouldn't be replaced by 1e30

2022-01-11 08:39 UTC, prateekreddy commented on contracts/PriceOracle.sol
> +        uint256 _numTokens = OracleLibrary.getQuoteAtTick(_twapTick, 1e30, num, den);
Use `SCALING_FACTOR` instead of `1e30`

2022-01-11 09:04 UTC, saxenism commented on contracts/PriceOracle.sol
> +        uint256 _numTokens = OracleLibrary.getQuoteAtTick(_twapTick, 1e30, num, den);
Done

2022-01-11 09:05 UTC, saxenism commented on contracts/PriceOracle.sol
> +        return (_numTokens, SCALING_FACTOR);
Done

2022-01-11 09:05 UTC, saxenism commented on contracts/PriceOracle.sol
> +        return (price, SCALING_FACTOR);
Done

2022-01-11 09:06 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +    uint256 constant SCALING_FACTOR = 1e30;
True, it was only being used for explanations in Natspec comments. Removed this declaration and changed the Natspec docs from using the SCALING_FACTOR to 10**30

2022-01-11 09:27 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +    uint256 constant SCALING_FACTOR = 1e30;
hmm instead probably use `SCALING_FACTOR(10**30)` ? That would probably be more clear

2022-01-11 09:29 UTC, prateekreddy requested changes

2022-01-11 09:29 UTC, prateekreddy commented on contracts/PriceOracle.sol
> +    uint256 constant SCALING_FACTOR = 1e30;
Use 10**(SCALING_NUMBER) instead

2022-01-11 09:39 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +    uint256 constant SCALING_FACTOR = 1e30;
Yes, agreed. That would definitely be more clear, but I wanted to incorporate the suggestions over at https://github.com/code-423n4/2021-12-sublime-findings/issues/126 

Let me know if you think we should ignore this.

2022-01-11 09:42 UTC, saxenism commented on contracts/PriceOracle.sol
> +    uint256 constant SCALING_FACTOR = 1e30;
We can do that. But then it would not be in line with this https://github.com/code-423n4/2021-12-sublime-findings/issues/126

Let me know if you think we can ignore this.

2022-01-12 07:05 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +    uint256 constant SCALING_FACTOR = 1e30;
Done. Please review again.

2022-01-12 07:05 UTC, saxenism commented on contracts/PriceOracle.sol
> +    uint256 constant SCALING_FACTOR = 1e30;
Done. Please review again.

2022-01-17 16:44 UTC, ritik99 reviewed
Check [line 675](https://github.com/sublime-finance/sublime-v1/blob/b1718b676dcdda936309f04ed8bb18e097bcf8cd/contracts/Pool/Pool.sol#L675), it could be changed to SCALING_FACTOR**2

2022-01-17 16:44 UTC, ritik99 commented on contracts/Pool/PoolFactory.sol
> +     * @return protocolFee Fraction multiplied by SCALING_FACTOR(SCALING_FACTOR(10**30))
extra SCALING_FACTOR

2022-01-17 16:44 UTC, ritik99 commented on contracts/PriceOracle.sol
> +    uint256 constant SCALING_NUMBER = 30;
Rename SCALING_NUMBER to SCALING_EXPONENT

2022-01-19 08:05 UTC, saxenism commented on contracts/PriceOracle.sol
> +    uint256 constant SCALING_NUMBER = 30;
Done.

2022-01-19 08:05 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +     * @return protocolFee Fraction multiplied by SCALING_FACTOR(SCALING_FACTOR(10**30))
Yep. Removed.

2022-01-19 17:52 UTC, merged