ETH asset added for liquidation
sublime-finance/sublime-v1 pull request #171
Opened 2021-12-27 10:55 UTC by saxenism

2022-01-11 09:02 UTC, prateekreddy requested changes

2022-01-11 09:02 UTC, prateekreddy commented on contracts/CreditLine/CreditLine.sol
> +		        require(success, 'liquidate: Transfer failed');
please take care of indentation

2022-01-13 08:27 UTC, saxenism commented on contracts/CreditLine/CreditLine.sol
> +		        require(success, 'liquidate: Transfer failed');
Done. Please review again.

2022-01-17 16:53 UTC, ritik99 commented on contracts/CreditLine/CreditLine.sol
> +		require(success, 'liquidate: Transfer failed');
Add line breaks to better differentiate between different actions, for eg, here the call + require is a combined action and can be separated above and below using line breaks

2022-01-19 08:06 UTC, saxenism commented on contracts/CreditLine/CreditLine.sol
> +		require(success, 'liquidate: Transfer failed');
Done.

2022-01-19 18:33 UTC, merged