Lime-86, Issue 65: PoolConstants packing
sublime-finance/sublime-v1 pull request #180
Opened 2021-12-27 19:35 UTC by KalpitaMandal

# Description
Stacked pull request on #178
In the `PoolConstants` struct we have a number of fields which don't need to take up an entire storage slot. Easy examples are the timestamps which can be placed in a `uint64` variable and packed with an address.

https://github.com/code-423n4/2021-12-sublime/blob/9df1b7c4247f8631647c7627a8da9bdc16db8b11/contracts/Pool/Pool.sol#L46-L59

This will save gas when performing the initial writes of these structs.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Restructured the `PoolConstants` struct (Issue 65: PoolConstants packing
Ref: https://github.com/code-423n4/2021-12-sublime-findings/issues/65)
```
struct PoolConstants {
        uint256 borrowAmountRequested;
        uint64 loanStartTime;
        address borrower;
        uint256 loanWithdrawalDeadline;
        uint256 idealCollateralRatio;
        uint256 borrowRate;
        uint256 noOfRepaymentIntervals;
        uint256 repaymentInterval;
        address collateralAsset;
        address borrowAsset;
        address poolSavingsStrategy; // invest contract
        address lenderVerifier;
    }
```

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-01-04 07:23 UTC, prateekreddy commented
Fixes https://github.com/code-423n4/2021-12-sublime-findings/issues/72

2022-01-04 07:23 UTC, prateekreddy commented
Fixes https://github.com/code-423n4/2021-12-sublime-findings/issues/129

2022-02-01 08:54 UTC, prateekreddy requested changes
Let's use uint256 in input args unless there is a gas optimisation.

2022-02-01 08:54 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +    using SafeMath for uint64;
This probably will not work.

2022-02-01 08:54 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          uint256 noOfRepaymentIntervals;
noOfRepaymentIntervals and repaymentInterval can probably be combined

2022-02-01 08:54 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 loanWithdrawalDeadline;
see if loanWithdrawalDeadline can also be combined with something else. Probably at the start with loanStartTime

2022-02-01 08:54 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint128 _borrowRate,
what is reasoning behind using uint128 here ?

2022-02-01 08:54 UTC, prateekreddy commented on contracts/Pool/Repayments.sol
> +    using SafeMath for uint128;
Is this needed ?

2022-02-01 08:54 UTC, prateekreddy commented on contracts/Pool/Repayments.sol
> +        uint128 borrowRate;
This can probably be combined with `numberOfTotalRepayments`

2022-02-01 16:53 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
> +    using SafeMath for uint64;
Removing this line gives the error: `TypeError: Member "mul" not found or not visible after argument-dependent lookup in uint64.`
However, the SafeMath libraries might convert uint64 to uint256 and might end up using more gas.
Looking more into it.

2022-02-02 09:01 UTC, KalpitaMandal commented on contracts/Pool/Repayments.sol
> +    using SafeMath for uint128;
Removing this line gives the following error
`TypeError: Member "mul" not found or not visible after argument-dependent lookup in uint128.`

2022-02-02 09:05 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
> +        uint128 _borrowRate,
I assumed borrow rate to always be less than 1e30 and hence uint128 can accomodate for the range of values. 
Can a user put more than a 100% borrow rate? In that case we might have to use uint256 itself.

2022-02-02 09:39 UTC, KalpitaMandal commented on contracts/Pool/Repayments.sol
> +        uint128 borrowRate;
made `numberOfTotalRepayments` as uint128 and combined with `borrowRate`

2022-02-02 09:57 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
>          uint256 noOfRepaymentIntervals;
Added the suggestion

2022-02-02 09:58 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
> +        uint256 loanWithdrawalDeadline;
Added the suggestion

2022-02-02 11:17 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint128 _borrowRate,
yes user can put more than 100% borrow rate. Also if uint128 is not getting packed, it will end up costing more gas

2022-02-03 04:17 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
> +    using SafeMath for uint64;
Typecasing to uint256 for using safeMath for calculations as only one place needed the change.

2022-02-03 04:18 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
> +        uint128 _borrowRate,
Added the change

2022-02-03 04:18 UTC, KalpitaMandal commented on contracts/Pool/Repayments.sol
> +    using SafeMath for uint128;
Typecasting to uint256 for calculations using safeMath as only two places needed the change.

2022-02-03 07:37 UTC, prateekreddy requested changes

2022-02-03 07:37 UTC, prateekreddy commented on contracts/Pool/Repayments.sol
> +        uint128 numberOfTotalRepayments; // using it to check if RepaymentDetails Exists as repayment Interval!=0 in any case
We can optimize this by combining with address if we decrease the uinnt128 to uint96 or lower

2022-02-03 07:51 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
> +        uint64 marginCallEndTime;
Added the change

2022-02-03 09:47 UTC, prateekreddy approved these changes

2022-02-03 10:17 UTC, merged