Lime-90, Issue 71: sending ETH when not expected
sublime-finance/sublime-v1 pull request #185
Opened 2021-12-28 06:23 UTC by KalpitaMandal

# Description
Stacked pull request on #184
Take for example the `depositCollateral` function. It's payable but the pool may not use ETH as collateral

https://github.com/code-423n4/2021-12-sublime/blob/9df1b7c4247f8631647c7627a8da9bdc16db8b11/contracts/Pool/Pool.sol#L175-L179

In the case where the user is performing a direct deposit then we'll pull in the erc20 collateral asset using the `transferTokens` function however there's no check for `msg.value == 0` when transferring an ERC20 asset.

https://github.com/code-423n4/2021-12-sublime/blob/9df1b7c4247f8631647c7627a8da9bdc16db8b11/contracts/SavingsAccount/SavingsAccountUtil.sol#L98-L127

Similarly when depositing ETH from a savings account any ETH in `msg.value `will be lost.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Adding require statement to check no ETH is sent where it is not required(Issue 71: sending ETH when not expected
Ref: https://github.com/code-423n4/2021-12-sublime-findings/issues/71)

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-02-01 10:06 UTC, prateekreddy commented
@KalpitaMandal Please ensure that this fix is applied on all instances where ETH can be received. Please check https://github.com/sublime-finance/sublime-v1/pull/289 for reference.

2022-02-01 10:07 UTC, prateekreddy requested changes
@KalpitaMandal Please ensure that this fix is applied on all instances where ETH can be received. Please check #289 for reference.

2022-02-01 14:53 UTC, KalpitaMandal commented
> @KalpitaMandal Please ensure that this fix is applied on all instances where ETH can be received. Please check #289 for reference.

Made additions to the rest of the payable functions.

2022-02-03 10:21 UTC, prateekreddy approved these changes

2022-02-04 05:15 UTC, prateekreddy approved these changes

2022-02-04 05:25 UTC, merged