added lend function.
sublime-finance/sublime-v1 pull request #2
Opened 2021-03-02 09:33 UTC by aditya26026

The lend function has been added. A revert message in withdrawBorrowedAmount had to be changed. Lastly chainLink have changed their directory structure, so had to correct that in PriceOracle.sol

2021-03-02 10:42 UTC, prateekreddy requested changes

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          require(
In the first check of collection and loanStartTime, copy loanStatus into a memory variable and then do the checks.

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          require(
loanStatus is being reused again and again, so use that as memory variable.

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          uint256 _currentCollateralRatio = getCurrentCollateralRatio();
Is getCurrentCollateralRatio function complete ?

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(_amountLent != 0, "Pool::lend - Invalid amount");
Do we need this check ? What happens if we don't check for this.

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +            totalSupply() != borrowAmountRequested,
Do we need this check ?

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(
Add a check to see if the pool is in collection period

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        // poolInfo.canBurn[msg.sender] == true;
remove the commented code

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        // Do we need to have a check that restricts the borrower from acting as a lender?
We cannot stop this anyways as identities are anon. So check not necessary.

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        if(borrowAsset == address(0)) {
Use borrowAsset as a memory variable as it is being read multiple times from storage.

2021-03-02 10:42 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        if(_amountLent.add(totalSupply()) > borrowAmountRequested) {
Use borrowAmountRequested as memory variable.

2021-03-02 10:48 UTC, aditya26026 commented on contracts/Pool/Pool.sol
>          uint256 _currentCollateralRatio = getCurrentCollateralRatio();
Some edges are left to be handled.

2021-03-02 10:51 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        require(_amountLent != 0, "Pool::lend - Invalid amount");
Nothing really. I will remove this.

2021-03-02 10:55 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +            totalSupply() != borrowAmountRequested,
Even this has no real use. Wil remove this.

2021-03-02 10:55 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        require(
done

2021-03-02 10:56 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        // poolInfo.canBurn[msg.sender] == true;
done

2021-03-02 10:56 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        if(borrowAsset == address(0)) {
done

2021-03-02 10:56 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        if(_amountLent.add(totalSupply()) > borrowAmountRequested) {
done

2021-03-02 10:56 UTC, aditya26026 commented on contracts/Pool/Pool.sol
>          require(
done

2021-03-02 11:02 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          uint256 _currentCollateralRatio = getCurrentCollateralRatio();
Let's complete  that because we will miss them out if we don't do that now.

2021-03-02 11:07 UTC, prateekreddy requested changes

2021-03-02 11:07 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 borrowAmountNeeded = borrowAmountRequested;
Use _ before memory variables, so that  it  is  easy for us to identify them

2021-03-02 11:07 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 borrowToken = borrowAsset;
Use _ before memory variables, so that it is easy for us to identify them

2021-03-02 11:12 UTC, aditya26026 commented on contracts/Pool/Pool.sol
>          uint256 _currentCollateralRatio = getCurrentCollateralRatio();
will work on this next.

2021-03-05 02:41 UTC, prateekreddy requested changes

2021-03-05 02:41 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +    function deposit(uint256 _amount,bool _isDirect) external payable override {
Rename to depositCollateral

2021-03-05 02:41 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 _liquidityshare = IYield(_investedTo).getTokensForShares(_amount, _collateralAsset);
Move this to line164 as this is only getting used there.

2021-03-05 02:41 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 _liquidityshare = IYield(_investedTo).getTokensForShares(_amount, _collateralAsset);
Move this to line 195

2021-03-05 02:41 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +                IERC20(collateralAsset).approve(_investedTo, _amount);
Approve is not necessary here

2021-03-05 02:41 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        ISavingAccount _savingAccount = ISavingAccount(IPoolFactory(PoolFactory).SavingAccount());
If the below logic for deposit is same for depositCollateral and addCollateralInMarginCall, why not seperate it out into a common internal function, something like _depositCollateral.

2021-03-05 02:41 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +                _poolStatus = LoanStatus.CANCELLED;
Should the pool be cancelled in this case ? If loan has started, but the extension period to match collateral is till going on. In that period if user tries to withdraw, then in that case, pool shouldn't be cancelled right, atleast until that collateral match period is complete.

2021-03-05 02:41 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          );
I am thinking if we should add a flag to check if amount is borrowed by user. There might be some edgecases like if the loan is repaid and no one actually collected the repayment, in that case also all these conditions will be satisfied and there might be enough amount in the pool for user to withdraw. So this can probably lead to attacks.

2021-03-05 02:41 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          );
Actually matchCollateralRatioEndTime value can be used instead of a new flag, add a check on this and ensure this is not zero, because this becomes 0 when amount is withdrawn and this is set when pool is created, so we can use this instead

2021-03-05 02:41 UTC, prateekreddy commented on contracts/interfaces/IPool.sol
> +    function deposit(uint256 _amount, bool _isDirect) external payable;
change to deposit collateral

2021-03-05 06:44 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +                _poolStatus = LoanStatus.CANCELLED;
This is for the case if say the lenders have not lent out the minimum borrowAmount.

2021-03-05 06:45 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +                _poolStatus = LoanStatus.CANCELLED;
matchCollateral is for the borrowers right.

2021-03-05 06:46 UTC, aditya26026 commented on contracts/Pool/Pool.sol
>          );
good point. Will make this change.

2021-03-05 07:16 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        ISavingAccount _savingAccount = ISavingAccount(IPoolFactory(PoolFactory).SavingAccount());
I have told @ayush2843 to do this. He will do this.

2021-03-06 07:56 UTC, prateekreddy requested changes

2021-03-06 07:56 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(loanStatus == LoanStatus.COLLECTION, "Pool::lend - The pool should be in Collection Period.");
Also check if the loanStartTime is not already reached. If reached, then revert. Because loanStatus doesn't get updated auto, so we might have to check for this where ever loanStartTime is used.

2021-03-06 07:56 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +            _poolStatus == LoanStatus.COLLECTION || (_poolStatus == LoanStatus.ACTIVE && block.timestamp<matchCollateralRatioEndTime), "Pool::cancelOpenBorrowPool - The pool cannot be cancelled when
block.timestamp<matchCollateralRatioEndTime probably covers all the cases right. This ensures that money is not withdrawn already.

2021-03-06 07:56 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(matchCollateralRatioEndTime == 0, "Pool::cancelOpenBorrowPool - The borrowedAmount has already been withdrawn.");
it is != 0, but anyways above require already fixes this. So this require is probably not necessary.

2021-03-06 07:56 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        emit OpenBorrowPoolCancelled();
When pool is cancelled, the borrower's collateral should be returned after a penalty right.

2021-03-06 07:56 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(
Actually it can be terminated any time.

2021-03-06 07:56 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +            emit LoanDefaulted();
When borrower withdrew or not, the entire collateral should be transferred to the admin right. If user took the lent amount by  then. There is nothing we can do.

2021-03-06 07:56 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(nextDuePeriod==0 && _totalAsset>totalSupply(), "Pool::closeLoan - The loan has not been fully repayed.");
_totalAsset can include alot of things right, so this might not be correct.

2021-03-06 08:03 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        require(loanStatus == LoanStatus.COLLECTION, "Pool::lend - The pool should be in Collection Period.");
right

2021-03-06 08:04 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +            _poolStatus == LoanStatus.COLLECTION || (_poolStatus == LoanStatus.ACTIVE && block.timestamp<matchCollateralRatioEndTime), "Pool::cancelOpenBorrowPool - The pool cannot be cancelled when
it seems correct. Will change this.

2021-03-06 08:06 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        require(matchCollateralRatioEndTime == 0, "Pool::cancelOpenBorrowPool - The borrowedAmount has already been withdrawn.");
yeah and removed it.

2021-03-06 08:07 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        emit OpenBorrowPoolCancelled();
Not really sure about this. Haven't really discussed this.

2021-03-06 08:07 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        require(
Can it be terminated after the pool is Defaulted, Closed or cancelled.

2021-03-06 08:07 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +            emit LoanDefaulted();
will change this.

2021-03-06 08:23 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        require(nextDuePeriod==0 && _totalAsset>totalSupply(), "Pool::closeLoan - The loan has not been fully repayed.");
Previously I had the thought to put the principle into the pool and the repayments in the repayments contract. So that is why I had used this condition. I am now assuming that after everything is repaid the variable nextDuePeriod would be set as 0.

2021-03-06 08:39 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(
Ohh yeah, I mean, it can be terminated when it is active  or collection

2021-03-06 10:44 UTC, prateekreddy approved these changes

2021-03-06 10:49 UTC, merged