Lime-131, Issue 166: missing nonreentrant modfier
sublime-finance/sublime-v1 pull request #202
Opened 2022-01-03 13:02 UTC by KalpitaMandal

# Description
Stacked pull request on #201
https://github.com/code-423n4/2021-12-sublime/blob/main/contracts/Pool/Pool.sol
missing non reentrant modifier in `terminatePool` , `requestMarginCall` and `initialize`.
all of the other functions of the contract have nonreentrant modifier therefore it's inconsistent.

# Integrations Checklist

- [x]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Adding reentrancy guard for consistency and security(Issue 166: missing nonreentrant modfier
Ref: https://github.com/code-423n4/2021-12-sublime-findings/issues/166)

# Event Signature Changes

# Function Signature Changes
- `function initialize(uint256 _borrowAmountRequested, uint256 _borrowRate, address _borrower, address _borrowAsset, address _collateralAsset, uint256 _idealCollateralRatio, uint256 _repaymentInterval, uint256 _noOfRepaymentIntervals, address _poolSavingsStrategy, uint256 _collateralAmount, bool _transferFromSavingsAccount, address _lenderVerifier, uint256 _loanWithdrawalDuration,  uint256 _collectionPeriod) external payable *nonReentrant* initializer`
- `function terminatePool() external *nonReentrant* onlyOwner`
- `function requestMarginCall() external *nonReentrant* isLender(msg.sender)`

# Features

# Events

2022-02-01 12:01 UTC, prateekreddy requested changes

2022-02-01 12:01 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +    ) external payable nonReentrant initializer {
Initializer by default cannot be run twice, so nonReentrant is not necessary, also initialiser is done by admin.

2022-02-01 14:00 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
> +    ) external payable nonReentrant initializer {
Removed from initializer

2022-02-04 07:00 UTC, prateekreddy approved these changes

2022-02-04 08:41 UTC, merged