Fixes-lime-68, Wrong emergencyWithdraw logic
sublime-finance/sublime-v1 pull request #216
Opened 2022-01-05 05:41 UTC by KalpitaMandal

# Description
Stacked pull request on #199
The method, `emergencyWithdraw` inside the contract `yield/NoYield` doesn't work as expected, the `transfer` was done with received value, and it should be done with amount, so the emergencyWithdraw never will work, always it will send 0 tokens.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Returning correct return values for emergency withdraw(Wrong emergencyWithdraw logic
There is a bug in emergency withdraw logic of no yield function as specified in issue https://github.com/code-423n4/2021-12-sublime-findings/issues/4)

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-02-01 12:04 UTC, prateekreddy requested changes

2022-02-01 12:04 UTC, prateekreddy commented on contracts/yield/NoYield.sol
> +        received = IERC20(_asset).balanceOf(address(this));
remove received var from the returns declaration and return received at the end of function

2022-02-01 13:57 UTC, KalpitaMandal commented on contracts/yield/NoYield.sol
> +        received = IERC20(_asset).balanceOf(address(this));
Done

2022-02-04 09:23 UTC, prateekreddy approved these changes

2022-02-04 09:24 UTC, merged