Lime-118, Issue 134: Yearn token <> shares conversion decimal issue
sublime-finance/sublime-v1 pull request #218
Opened 2022-01-05 07:49 UTC by KalpitaMandal

# Description
The yearn strategy `YearnYield` converts shares to tokens by doing `pricePerFullShare * shares / 1e18`:
```
function getTokensForShares(uint256 shares, address asset) public view override returns (uint256 amount) {
    if (shares == 0) return 0;
    // @audit should divided by vaultDecimals 
    amount = IyVault(liquidityToken[asset]).getPricePerFullShare().mul(shares).div(1e18);
}
```
But Yearn's `getPricePerFullShare` seems to be in `vault.decimals()` precision, i.e., it should convert it as `pricePerFullShare * shares / (10 ** vault.decimals())`.
The vault decimals are the same as the underlying token decimals

# Integrations Checklist

- [x]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Adding the correct precision for the token to share conversion (and vice versa) functions in YearnYield.sol(Issue 134: Yearn token <> shares conversion decimal issue
Ref: https://github.com/code-423n4/2021-12-sublime-findings/issues/134)
- Added the `decimals()` function definition in IyVaultsol contract.

# Event Signature Changes

# Function Signature Changes
- `function decimals() external view returns (uint256);` (Added)

# Features

# Events

2022-02-04 09:18 UTC, prateekreddy requested changes

2022-02-04 09:18 UTC, prateekreddy commented on contracts/yield/YearnYield.sol
> +        shares = (amount.mul(10 ** vault.decimals())).div(getTokensForShares(10 ** vault.decimals(), asset));
vault.decimals can be reused

2022-02-04 09:33 UTC, KalpitaMandal commented on contracts/yield/YearnYield.sol
> +        shares = (amount.mul(10 ** vault.decimals())).div(getTokensForShares(10 ** vault.decimals(), asset));
Added the changes

2022-02-04 09:56 UTC, prateekreddy requested changes

2022-02-04 09:56 UTC, prateekreddy commented on contracts/yield/YearnYield.sol
> +        amount = vault.getPricePerFullShare().mul(shares).div(10 ** vault.decimals());
Decimals for the vault can be stored when adding liquidityToken to the contract once and reused when needed.

2022-02-04 09:56 UTC, prateekreddy commented on contracts/yield/YearnYield.sol
> +        shares = (amount.mul(10 ** vaultDecimals)).div(getTokensForShares(10 ** vaultDecimals, asset));
Using vaultDecimals is probably not necessary but it is better to use as decimals because it will help give reasonable amounts while getting tokensforshares

2022-02-04 10:33 UTC, KalpitaMandal commented on contracts/yield/YearnYield.sol
> +        amount = vault.getPricePerFullShare().mul(shares).div(10 ** vault.decimals());
Added this change

2022-04-18 11:41 UTC, prateekreddy commented
Yearn is not being used. Hence closing the PR

2022-04-18 11:41 UTC, closed without merging