CS Audit, Lime 220, Removed unused enum state
sublime-finance/sublime-v1 pull request #249
Opened 2022-01-11 06:45 UTC by saxenism

## Description

In CreditLine the CreditLineStatus has the definition CANCELLED. This definition is never used and therefore can be removed.

## Integration Checklist

- [ ] Make sure all existing tests should pass
- [ ] Gas costs reduction can be compared using gasReport.md

## Changelog

An unused enum state was removed from CreditLines.

2022-01-13 07:51 UTC, prateekreddy requested changes

2022-01-13 07:51 UTC, prateekreddy commented on contracts/CreditLine/CreditLine.sol
> -        CANCELLED,
Can you add a function to cancel the credit line when it is not yet accepted ?

2022-01-13 08:03 UTC, saxenism commented on contracts/CreditLine/CreditLine.sol
> -        CANCELLED,
Please refer to https://github.com/sublime-finance/sublime-v1/pull/257

Let me know if you want me to make that changes here.

2022-01-16 10:57 UTC, prateekreddy commented
duplicate of #257

2022-01-16 10:57 UTC, closed without merging