CS Audit, Lime 191, Renamed poolFactory modifier
sublime-finance/sublime-v1 pull request #251
Opened 2022-01-11 06:58 UTC by saxenism

## Description

The PoolFactory contract implements a modifier as shown below: 

modifier onlyBorrower(address _verifier) { require( IVerification(userRegistry).isUser(msg.sender, _verifier), 'PoolFactory::onlyBorrower - Only a valid Borrower can create Pool' ); _; } 

The name onlyBorrower implies that only a borrower of a pool can call functions protected by this modifier, however, the modifier only checks that the msg.sender has been verified by _verifier and not if it is a borrower of a pool.

## Integration Checklist

- [ ] The exisiting tests should not break.

## Change Log

The name of the `onlyBorrower` modifier in PoolFactory.sol has been changed to a more appropriate `onlyVerified`.

2022-01-13 08:13 UTC, prateekreddy requested changes

2022-01-13 08:13 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +     * @notice functions affected by this modifier can only be invoked by the borrower (verified user) of the Pool
actually let's probably remove borrower stuff, we just need to say that it is invoked by verified user na... borrower stuff is secondary and might not apply everywhere.

2022-01-13 09:22 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +     * @notice functions affected by this modifier can only be invoked by the borrower (verified user) of the Pool
True. Made the changes. Please review again.

2022-01-16 10:23 UTC, prateekreddy approved these changes

2022-01-16 10:23 UTC, merged