CS Audit, Lime 192, Added Sanity checks on share transfer
sublime-finance/sublime-v1 pull request #252
Opened 2022-01-11 07:01 UTC by saxenism

## Description

The function transfer does not perform sanity checks for the parameter _to. Hence, it is possible to send to address zero and effectively "burn" the shares from the saving strategies during transfer.

## Integration Checklist

- [ ] Add tests which check calling the transfer function with _to address set as 0.

## Change Log

Sanity check was added to `SavingsAccount.transfer` function.

2022-01-13 08:27 UTC, prateekreddy requested changes

2022-01-13 08:27 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), 'The to address should be a valid address');
In this case, we need a seperate function for burn... Can you look into it ?

2022-01-20 07:26 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), 'The to address should be a valid address');
Yes, agreed. Added the burn function. This burn function only takes care of burning the corresponding shares of the user's tokens in the savings account particular strategy. Burning of directly the tokens is not implemented and left to the users.

2022-01-24 11:42 UTC, ritik99 commented on contracts/SavingsAccount/SavingsAccount.sol
> +        if(_strategy != address(0)) {
We're using no yield strat now, is this still valid?

2022-01-24 12:45 UTC, ritik99 commented on contracts/SavingsAccount/SavingsAccount.sol
> +        balanceInShares[msg.sender][_token][_strategy] = balanceInShares[msg.sender][_token][_strategy].sub(
check the current balance first before subtraction

2022-01-25 17:19 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        balanceInShares[msg.sender][_token][_strategy] = balanceInShares[msg.sender][_token][_strategy].sub(
Yes, if you see the full statement about subtraction here: https://github.com/sublime-finance/sublime-v1/blob/chainsec-lime-192/contracts/SavingsAccount/SavingsAccount.sol#L483
Then you'll see that I've added a check to see that the subtraction only goes through if there is enough balance.

Let me know if you think this is not appropriate, I'll replace this with a `require` statement in that case.

2022-01-25 18:39 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        if(_strategy != address(0)) {
True, there is an `NoYield` contract now and we could have called that contract like `IYield(_strategy).getSharesForTokens(_amount, _token)` but as you can see in the `NoYield` contract itself here https://github.com/sublime-finance/sublime-v1/blob/chainsec-lime-192/contracts/yield/NoYield.sol#L176 that it will only waste gas, as no operation is being performed in the `getSharesForTokens` function in `NoYield` hence I think this change is pretty much valid.

2022-01-25 18:55 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        if(_strategy != address(0)) {
Hmm, I get what you're saying now. The `if` block was redundant. Have removed that.

2022-01-28 10:10 UTC, prateekreddy requested changes

2022-01-28 10:10 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), "SavingsAccounts::_transfer _to address should be non-zero");
We are doing multiple check on to!= address(0), for example, withdraw function checks for this twice. Let's optimize that part

2022-01-28 10:10 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(IStrategyRegistry(strategyRegistry).registry(_strategy), 'SavingsAccount::burn strategy do not exist');
Any specific reason we are checking for strategy here ?

2022-01-28 10:44 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(IStrategyRegistry(strategyRegistry).registry(_strategy), 'SavingsAccount::burn strategy do not exist');
The only reason is for sanitising the strategy address, so that no-one passes an invalid strategy address to burn their shares from.

Should I remove this check?

2022-01-28 10:44 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), "SavingsAccounts::_transfer _to address should be non-zero");
Ha true, the `function withdraw` does check if the `_to` address is not zero. But I re-checked that no function which is calling this specific `function _transfer` function is making this `_to` address check.

Please review again.

2022-01-31 09:22 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(IStrategyRegistry(strategyRegistry).registry(_strategy), 'SavingsAccount::burn strategy do not exist');
yeah, because it is possible that user wants to burn tokens if the strategy is considered invalid. So probably this is not needed.

2022-01-31 11:59 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(IStrategyRegistry(strategyRegistry).registry(_strategy), 'SavingsAccount::burn strategy do not exist');
Cool. Removed this check.

2022-01-31 14:20 UTC, prateekreddy approved these changes

2022-01-31 14:35 UTC, merged