CS Audit, Lime 181, Stacked requires together
sublime-finance/sublime-v1 pull request #253
Opened 2022-01-11 07:06 UTC by saxenism

## Description

The following function in SavingsAccount 

deposit(uint256 _amount, address _token, address _strategy, address _to) 

does a single sanity check for the _to parameter, then calls the internal function _deposit which does another sanity check for the amount parameter. Next, function _depositToYield is called which does another sanity check for the initial parameter _strategy. 

It is a good practice to do all such checks first in the initial function when possible, e.g., deposit, instead of splitting them among multiple functions. Other examples: 

• require(_lender != _borrower) in _createRequest. 

• require(creditLineConstants[_id].lender != msg.sender) in _depositCollateral.

## Integration Checklist

- [ ] The existing tests shouldn't break

## Change Log

Different require statements were stacked together in the SavingsAccount.sol smart contract.

2022-01-13 08:38 UTC, prateekreddy requested changes

2022-01-13 08:38 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> -        require(IStrategyRegistry(strategyRegistry).registry(_strategy), 'SavingsAccount::deposit strategy do not exist');
`_depositToYield` has been used in multiple functions. So the check needs to be migrated to other functions as well

2022-01-13 10:11 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> -        require(IStrategyRegistry(strategyRegistry).registry(_strategy), 'SavingsAccount::deposit strategy do not exist');
Yes, correct. Migrated the require function to the required functions. Please review once again.

2022-01-16 10:25 UTC, prateekreddy approved these changes

2022-01-16 10:25 UTC, merged