CS Audit, LIME 196, Added sanity checks
sublime-finance/sublime-v1 pull request #254
Opened 2022-01-11 08:22 UTC by saxenism

## Description

The following functions do not perform any sanity check: _updateCollectionPeriod, _updateLoanWithdrawalDuration, _updateMarginCallDuration, _updatePoolLogic, etc.

## Integration Checklist

- [ ] Write tests for making sure the sanity checks work now

## Change Log
Sanity checks were added to the PoolFactory contract

2022-01-13 08:45 UTC, prateekreddy requested changes

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_collectionPeriod > 0, "PoolFactory:_updateCollectionPeriod _collectionPeriod should be greater than zero");
it is an uint256 so it is already unsigned and hence cant be negative

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_loanWithdrawalDuration > 0, "PoolFactory:_updateLoanWithdrawalDeadline _loanWithdrawalDuration should be greater than zero");
it is an uint256 so it is already unsigned and hence cant be negative

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_marginCallDuration > 0, "PoolFactory:updateMarginCallDuration _marginCallDuration should be greater than 0");
it is an uint256 so it is already unsigned and hence cant be negative

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_poolCancelPenaltyMultiple <= 10**30,"PoolFactory:_updatePoolCancelPenaltyMultiple _poolCancelPenaltyMultiple cannot be more than 100%");
This might not be true as cancel penality multiple is  multiplied by interest rate

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_min > 0, 'PoolFactory:updatePoolSizeLimit _min should be greater than zero');
it is an uint256 so it is already unsigned and hence cant be negative

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_min >= 0, "PoolFactory:updateidealCollateralRatioLimit _min should atleast be zero");
!= 0 should suffice as it cant be negative

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_min > 0, "PoolFactory:updateBorrowRateLimit _min should be greater than zero");
it is an uint256 so it is already unsigned and hence cant be negative

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_min > 0, "PoolFactory:updateRepaymentIntervalLimit _min should be greater than zero");
it is an uint256 so it is already unsigned and hence cant be negative

2022-01-13 08:45 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_min > 0,"PoolFactory:updateNoOfRepaymentIntervalsLimit _min should be greater than zero");
it is an uint256 so it is already unsigned and hence cant be negative

2022-01-20 10:13 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_min > 0, "PoolFactory:updateRepaymentIntervalLimit _min should be greater than zero");
Resolved.

2022-01-20 10:14 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_min > 0,"PoolFactory:updateNoOfRepaymentIntervalsLimit _min should be greater than zero");
Resolved.

2022-01-20 10:14 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_min > 0, "PoolFactory:updateBorrowRateLimit _min should be greater than zero");
Resolved.

2022-01-20 10:14 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_min >= 0, "PoolFactory:updateidealCollateralRatioLimit _min should atleast be zero");
Resolved.

2022-01-20 10:14 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_min > 0, 'PoolFactory:updatePoolSizeLimit _min should be greater than zero');
Resolved.

2022-01-20 10:14 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_poolCancelPenaltyMultiple <= 10**30,"PoolFactory:_updatePoolCancelPenaltyMultiple _poolCancelPenaltyMultiple cannot be more than 100%");
Resolved.

2022-01-20 10:14 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_marginCallDuration > 0, "PoolFactory:updateMarginCallDuration _marginCallDuration should be greater than 0");
Resolved.

2022-01-20 10:14 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_loanWithdrawalDuration > 0, "PoolFactory:_updateLoanWithdrawalDeadline _loanWithdrawalDuration should be greater than zero");
Resolved.

2022-01-20 10:14 UTC, saxenism commented on contracts/Pool/PoolFactory.sol
> +        require(_collectionPeriod > 0, "PoolFactory:_updateCollectionPeriod _collectionPeriod should be greater than zero");
Resolved.

2022-01-24 10:24 UTC, ritik99 requested changes
Replace 10**30 with SCALING_FACTOR that has been used elsewhere

2022-01-24 10:24 UTC, ritik99 commented on contracts/Pool/PoolFactory.sol
> +        require(_min != 0, "PoolFactory:updateidealCollateralRatioLimit _min should be non-zero");
This check is not necessary

2022-01-24 10:24 UTC, ritik99 commented on contracts/Pool/PoolFactory.sol
> +        require(_min != 0,"PoolFactory:updateNoOfRepaymentIntervalsLimit _min should be non-zero");
Not necessary

2022-02-01 06:28 UTC, prateekreddy commented on contracts/Pool/PoolFactory.sol
> +        require(_min != 0,"PoolFactory:updateNoOfRepaymentIntervalsLimit _min should be non-zero");
We can use noOfRepaymetIntervals as 1 if we need everything to be repaid in one go.

2022-02-01 06:31 UTC, prateekreddy approved these changes

2022-02-01 06:31 UTC, merged