CS Audit, Lime 218, Added checks for strategy addresses
sublime-finance/sublime-v1 pull request #256
Opened 2022-01-11 08:46 UTC by saxenism

## Description

There are multiple calls to the strategy contract. But the user is allowed to pass in the strategy. Hence, it remains unclear if a whitelisted strategy or a malicious contract is called. We could not find any severe impact but e.g., in transfer and transferFrom in the SavingsAccount contract, the strategy contract is called without being checked if it is a valid strategy.

## Integration Checklist

- [ ] Write tests that check passing of unsanitized strategy addresses

## Change Log

Sanity checks were added to check the address of strategy addresses in `transfer` and `transferFrom` function in `SavingsAccount.sol`.

2022-01-11 14:41 UTC, prateekreddy requested changes

2022-01-11 14:41 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), "SavingsAccount:transfer _to should be a non-zero address");
This check is not necessary because sending tokens to address(0) represents burning the tokens and hence a valid usecase

2022-01-11 14:41 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), "SavingsAccount:transferFrom _to should be a non-zero address");
This check is not necessary because sending tokens to address(0) represents burning the tokens and hence a valid usecase

2022-01-11 14:41 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(IStrategyRegistry(strategyRegistry).registry(_strategy), 'SavingsAccount::deposit strategy do not exist');
wrong revert message, it should be SavingsAccount::transferFrom

2022-01-12 07:12 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(IStrategyRegistry(strategyRegistry).registry(_strategy), 'SavingsAccount::deposit strategy do not exist');
Done. Please review again.

2022-01-12 07:12 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), "SavingsAccount:transferFrom _to should be a non-zero address");
Done. Please review again.

2022-01-12 07:12 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), "SavingsAccount:transfer _to should be a non-zero address");
Done. Please review again.

2022-01-13 08:48 UTC, prateekreddy requested changes

2022-01-13 08:48 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), "SavingsAccount:transfer _to should be a non-zero address");
Not resolved yet, can you check ?

2022-01-13 10:23 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +        require(_to != address(0), "SavingsAccount:transfer _to should be a non-zero address");
Yeah, missed this. Had only removed the `require` from the `transferFrom` function and not the `transfer` function. Please review again.

2022-01-16 10:28 UTC, prateekreddy approved these changes

2022-01-16 10:28 UTC, merged