CS Audit, Lime 206, Gas opt in creditline closure
sublime-finance/sublime-v1 pull request #257
Opened 2022-01-11 09:29 UTC by saxenism

## Description

A credit line uses two struct variables CreditLineConstants and CreditLineVariables which occupy storage when a credit line is created. When a credit line is closed, the status variable is set to CLOSED but the occupied storage is not freed.

## Integration Checklist

- [ ] Write tests calling public/external functions after a particular creditline has been closed and make sure that no function throws unexpected values
- [ ] Savings in gas cost can be compared using gasReport.md

## Change Log
Once a credit line has been closed, the associated creditLineConstants and creditLineVariables are deleted.

2022-01-11 09:46 UTC, saxenism commented
Topic for discussion @ritik99 @prateekreddy @prateekreddy @KalpitaMandal 

With the above PR, if approved, I don't think we would really need the `CLOSED` enum state too. Let me know what you all think.

2022-01-11 14:33 UTC, prateekreddy requested changes

2022-01-11 14:33 UTC, prateekreddy commented on contracts/CreditLine/CreditLine.sol
>          creditLineVariables[_id].status = CreditLineStatus.CLOSED;
This line needs to be removed

2022-01-12 07:31 UTC, saxenism commented on contracts/CreditLine/CreditLine.sol
>          creditLineVariables[_id].status = CreditLineStatus.CLOSED;
Removed. Please review again.

2022-01-12 07:32 UTC, saxenism commented
> Topic for discussion @ritik99 @prateekreddy
> 
> With the above PR, if approved, I don't think we would really need the `CLOSED` enum state in the `creditLineStatus` too. Let me know what you all think.

The above topic was discussed on team meet and I have removed the `CLOSED` state as well as introduced a `cancel` function to cancel creditline requests without adding a `CANCELLED` state.

2022-01-19 18:11 UTC, merged