CS Audit, Lime 170, Added description of the return value
sublime-finance/sublime-v1 pull request #258
Opened 2022-01-11 10:02 UTC by saxenism

## Description

Return value of `SavingsAccount.transferFrom` lacks description

## Change Log

Natpsec comment of `SavingsAccount.transferFrom` was improved.

2022-01-11 14:31 UTC, prateekreddy requested changes

2022-01-11 14:31 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +     * @return the amount of tokens in terms of _token that will be transferred from the
the amount is not in _token but the LP token for _token in strategy

2022-01-12 08:03 UTC, saxenism commented on contracts/SavingsAccount/SavingsAccount.sol
> +     * @return the amount of tokens in terms of _token that will be transferred from the
Yes, correct. Had gotten a bit confused. Please review again.

2022-01-13 09:21 UTC, prateekreddy approved these changes

2022-01-13 09:21 UTC, merged