CS Audit, Lime 173, Corrected the docs
sublime-finance/sublime-v1 pull request #259
Opened 2022-01-11 10:16 UTC by saxenism

## Description

The function Repayments.getInterestOverdue has a wrong description since it considers a case when there is a loan extension.

## Change Log

Erroneous function description was corrected.

2022-01-11 14:29 UTC, prateekreddy requested changes

2022-01-11 14:29 UTC, prateekreddy commented on contracts/Pool/Extension.sol
> +import '@openzeppelin/contracts/math/SafeMath.sol';
Why was this change necessary ?

2022-01-12 08:11 UTC, saxenism commented on contracts/Pool/Extension.sol
> +import '@openzeppelin/contracts/math/SafeMath.sol';
According to an earlier issue, we found that `Extension.sol` imports SafeERC20.sol, but it is not used in the contract anywhere, so I had first removed it, but then the contract was using SafeMath for uint256.... so, I had to import `math/SafeMath`.
This essentially means that before this, the only use of `token/ERC20/SafeERC20` was enabling the use of SafeMath and nothing else.

Apart from that, since you've already approved PR#248 (https://github.com/sublime-finance/sublime-v1/pull/248) not making this change would have created merge conflict also.

2022-01-13 09:22 UTC, prateekreddy approved these changes

2022-01-13 09:22 UTC, merged