CS Audit, Lime 174, Improved documentation
sublime-finance/sublime-v1 pull request #260
Opened 2022-01-11 10:24 UTC by saxenism

## Description

In AaveYield.sol
• The specification for the `unlockShares` refers to the asset as the underlying token, but the code assumes to be the Aave token. 

• In _withdrawETH the comment lock collateral is incorrect.

## Change Log

Erroneous documentation were corrected.

2022-01-11 13:20 UTC, prateekreddy requested changes

2022-01-11 13:20 UTC, prateekreddy commented on contracts/yield/AaveYield.sol
> +     * @param asset the address of underlying token, which in this would always be Aave tokens
Let's instead use underlying asset only here and change all the instances where this is used

2022-01-11 13:20 UTC, prateekreddy commented on contracts/yield/AaveYield.sol
> +     * @param asset the address of underlying token, which in this would always be Aave tokens
It will save gas costs as we are making multiple calls to yield which can be avoided

2022-01-28 11:01 UTC, saxenism commented on contracts/yield/AaveYield.sol
> +     * @param asset the address of underlying token, which in this would always be Aave tokens
This is done. Please check again.

2022-01-31 09:16 UTC, prateekreddy requested changes

2022-01-31 09:16 UTC, prateekreddy commented on contracts/yield/AaveYield.sol
> +            return (0, address(0));
Let's still return the correct liquidityToken for correctness

2022-01-31 10:47 UTC, saxenism commented on contracts/yield/AaveYield.sol
> +            return (0, address(0));
Yes, correct. Changed the return value. 

Please review again.

2022-01-31 13:45 UTC, prateekreddy approved these changes

2022-01-31 14:36 UTC, merged