CS lime-189, Inefficient Struct Packing
sublime-finance/sublime-v1 pull request #265
Opened 2022-01-11 13:03 UTC by KalpitaMandal

# Description

The struct `ExtensionVariables` has three variables of type `uint256`. At least the time and interval variables could be packed together to save a slot as it is highly unlikely, that these variables need a full word.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Efficient struct packing in `Extension.sol`.

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-01-11 13:32 UTC, prateekreddy requested changes

2022-01-11 13:32 UTC, prateekreddy commented on contracts/Pool/Extension.sol
>          uint256 repaymentInterval;
May be we can combine repaymentInterval as well with the first 2 vars, because bool takes 8 bits only.

2022-01-11 13:34 UTC, prateekreddy commented on contracts/Pool/Extension.sol
> +        mapping(address => uint64) lastVotedExtension;
mapping can be uint256 only, we will end up spending more gas if we use uint64

2022-01-11 14:00 UTC, KalpitaMandal commented on contracts/Pool/Extension.sol
> +        mapping(address => uint64) lastVotedExtension;
reverted to uint256

2022-01-11 14:04 UTC, KalpitaMandal commented on contracts/Pool/Extension.sol
>          uint256 repaymentInterval;
Packing `repaymentInterval` further using uint128

2022-01-13 09:44 UTC, prateekreddy approved these changes

2022-01-13 09:44 UTC, merged