CS lime-209, Recalculation of Shares
sublime-finance/sublime-v1 pull request #269
Opened 2022-01-11 14:42 UTC by KalpitaMandal

# Description
The _depositCollateralFromSavingsAccount in the CreditLine contract calculates the shares transferred and then adds them into the balance:

collateralShareInStrategy[_id][_strategy] = collateralShareInStrategy[_id][_strategy].add( _liquidityShares.mul(_tokensToTransfer).div(_tokenInStrategy) );

Instead of recalculating the shares, the function can use the return value of the external call transferFrom which returns the share amount.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Using return values instead of re-calculating the shares in `_depositCollateralFromSavingsAccount` in the `CreditLine.sol`.

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-01-17 04:51 UTC, prateekreddy requested changes

2022-01-17 04:51 UTC, prateekreddy commented on contracts/CreditLine/CreditLine.sol
> +                _savingsAccount.transferFrom(_tokensToTransfer, _collateralAsset, _strategy, _sender, address(this))
Create a local variable to hold the return value of transferFrom so that code is more readable

2022-01-28 09:54 UTC, KalpitaMandal commented on contracts/CreditLine/CreditLine.sol
> +                _savingsAccount.transferFrom(_tokensToTransfer, _collateralAsset, _strategy, _sender, address(this))
Tried storing a local variable but was facing stack too deep error.

2022-01-31 14:38 UTC, prateekreddy commented on contracts/CreditLine/CreditLine.sol
> +                _savingsAccount.transferFrom(_tokensToTransfer, _collateralAsset, _strategy, _sender, address(this))
We might have to update the code such that we can avoid stack too deep, by restricting scope of certain variables

2022-01-31 16:07 UTC, KalpitaMandal commented on contracts/CreditLine/CreditLine.sol
> +                _savingsAccount.transferFrom(_tokensToTransfer, _collateralAsset, _strategy, _sender, address(this))
PR #275 invalidates this change. 
The above PR removes the return values sent by `transferFrom` function so the change made in this PR becomes invalid.
We might have to go back to the original version for this issue.
Need discussion.

2022-02-01 08:10 UTC, prateekreddy approved these changes

2022-02-01 08:10 UTC, merged