CS lime-216, Unchecked Return Values
sublime-finance/sublime-v1 pull request #275
Opened 2022-01-11 17:27 UTC by KalpitaMandal

# Description

Multiple functions return a value which is not checked or used in the calling function. e.g.: 

• withdrawFrom in _withdrawBorrowAmount. 

• transfer and withdraw in _transferCollateral. 

• deposit in _repay. 

• transferFrom in _depositCollateralFromSavingsAccount and _repayFromSavingsAccount.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Removing unwanted returns from the function `transferFrom` from the `SavingsAccount.sol`

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-01-16 11:12 UTC, prateekreddy requested changes
This issue need to be fixed as this function is also used for directly depositing to savings account, in which case a return value might be necessary

2022-01-29 11:32 UTC, KalpitaMandal commented
> This issue need to be fixed as this function is also used for directly depositing to savings account, in which case a return value might be necessary

The return value in `directDeposit` does not depend on `transferFrom`, rather the amount specified in the arguments is returned.

2022-01-31 08:50 UTC, prateekreddy commented
Current implementation of return values is inconsistent. `transfer` and `transferFrom` has different return values.

2022-01-31 14:09 UTC, prateekreddy approved these changes

2022-01-31 14:23 UTC, merged