CS lime-160, Wrong Calculation of _maxPossible in CreditLine
sublime-finance/sublime-v1 pull request #278
Opened 2022-01-11 18:56 UTC by KalpitaMandal

# Description
The calculateBorrowableAmount computes _maxPossible as follows: 
```
uint256 _maxPossible = _totalCollateralToken.mul(_ratioOfPrices) .div(creditLineConstants[_id].idealCollateralRatio).div(10**_decimals); 
```
The decimals of the variables above are listed: • _totalCollateralToken is in collateral token's decimals. • ratioOfPrices is in 30 decimals. • idealCollateralRatio is in 30 decimals. • _decimals is equal to 30. A simplified version of the above formula with corresponding decimals in square brackets is: _maxPossible = (_totalCollateralToken[x] * ratioOfPrices[30])[y] / (idealColl ateralRatio[30] * 10 ^ 30), where x is the decimals of the collateral token and y is the decimals of borrow token. This shows that the result has y - 30 decimals instead of y.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Fixing the calculation of `_maxPossible` variable in `Creditline.sol`

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-01-17 05:13 UTC, prateekreddy approved these changes

2022-01-17 05:13 UTC, prateekreddy requested changes
Fix tests

2022-02-04 06:58 UTC, KalpitaMandal commented
> Fix tests

Merging with v1-alpha fixes the tests

2022-02-04 08:33 UTC, prateekreddy approved these changes

2022-02-04 08:33 UTC, prateekreddy commented
Fix is already applied in a different commit

2022-02-04 08:33 UTC, closed without merging