CS lime-158, Wrong Calculation of Collateral Ratio in CreditLine
sublime-finance/sublime-v1 pull request #282
Opened 2022-01-11 19:23 UTC by KalpitaMandal

# Description
The borrow function in CreditLine computes the collateral ratio before an _amount is borrowed as follows: 
```
uint256 _collateralRatioIfAmountIsWithdrawn = _ratioOfPrices.mul(_totalCollateralToken) .div((_currentDebt.add(_amount)).mul(10**_decimals)); 
```
A simplified version of the above formula with corresponding decimals in square brackets is: (_ratioOfPrices[30] * _totalCollateralToken[x] * 10^30)/(_currentDebt + _amou nt)[y], where x is the decimals of the collateral token and y is the decimals of the borrow token. The result is in other decimals than 30.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Adding correct calculation for collateral ratio.

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-01-17 05:01 UTC, prateekreddy requested changes

2022-01-17 05:01 UTC, prateekreddy commented on contracts/CreditLine/CreditLine.sol
> +        uint256 _collateralRatioIfAmountIsWithdrawn = _ratioOfPrices.mul(_totalCollateralToken).mul(10**30).div(
Need to handle possible  overflow

2022-02-04 06:57 UTC, KalpitaMandal commented on contracts/CreditLine/CreditLine.sol
> +        uint256 _collateralRatioIfAmountIsWithdrawn = _ratioOfPrices.mul(_totalCollateralToken).mul(10**30).div(
The variable was removed and no overflow detected for the new function flow

2022-02-04 08:29 UTC, prateekreddy commented
The borrow function uses a different way to calculate borrowable amount and hence the above logic is not used anymore.

2022-02-04 08:29 UTC, closed without merging