CS lime-159, Wrong Calculation of Current Collateral Ratio in CreditLine
sublime-finance/sublime-v1 pull request #283
Opened 2022-01-11 19:28 UTC by KalpitaMandal

# Description
The calculateCurrentCollateralRatio function in CreditLine computes the current collateral ratio as follows: 
```
uint256 currentCollateralRatio = calculateTotalCollateralTokens(_id).mul(_ratioOfPrices) .div(currentDebt).div(10**_decimals); 
```
A simplified version of the above formula with corresponding decimals in square brackets is: (_totalCollateralToken[x] * _ratioOfPrices[30])/(_currentDebt[y] * 10^30), where x is the decimals of the collateral token and y is the decimals of the borrow token. The result has other decimals than 30 - the expected decimals of the collateral ratio.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Fixing the calculation of current collateral ratio in `Creditline.sol`

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-01-17 04:59 UTC, prateekreddy requested changes

2022-01-17 04:59 UTC, prateekreddy commented on contracts/CreditLine/CreditLine.sol
> +        uint256 currentCollateralRatio = calculateTotalCollateralTokens(_id).mul(_ratioOfPrices).mul(10**30).div(currentDebt).div(10**_decimals);
overflow can happen here, based on total collateral tokens, need to account for that

2022-02-04 06:57 UTC, KalpitaMandal commented on contracts/CreditLine/CreditLine.sol
> +        uint256 currentCollateralRatio = calculateTotalCollateralTokens(_id).mul(_ratioOfPrices).mul(10**30).div(currentDebt).div(10**_decimals);
Added the changes.

2022-02-04 08:27 UTC, prateekreddy approved these changes

2022-02-04 08:27 UTC, merged