CS lime-203, Not Accounted Ether Transfers
sublime-finance/sublime-v1 pull request #289
Opened 2022-01-14 06:24 UTC by KalpitaMandal

# Description
Multiple times the code checks whether the asset address is address zero. If so, it checks if the ether amount equals the provided amount argument `msg.value == amount`. In the case of token operations, it is not checked if Ether was sent in the same transaction. Ether might be sent accidentally in the transaction as the functions are payable. That Ether would not be accounted for.

# Integrations Checklist

- [ ]  Have any function signatures changed? If yes, outline below.
- [ ]  Have any features changed or been added? If yes, outline below.
- [ ]  Have any events changed or been added? If yes, outline below.
- [ ]  Has all documentation been updated?

# Changelog

- Assigning `msg.value` to zero in the following contracts, where ETH transfers are not required:
  - `CreditLine.sol`
  - `Pool.sol`
  - `Repayments.sol`
  - `SavingsAccount.sol`

# Event Signature Changes

# Function Signature Changes

# Features

# Events

2022-01-16 10:38 UTC, prateekreddy commented
Missed  this check in `_repay` function from creditLines

2022-01-16 10:43 UTC, prateekreddy requested changes

2022-01-16 10:43 UTC, prateekreddy commented on contracts/CreditLine/CreditLine.sol
> +            require(msg.value == 0, 'DepositCollateral: ETH is not required for this operation');
This can be move to _depositCollateral function for gas optimization

2022-01-16 10:43 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        if(Address(poolConstants.collateralAsset) != Address(0) || _transferFromSavingsAccount) {
These checks can be move to the savingsAccountUtil functions which will make it more efficient

2022-01-16 10:43 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +            require(msg.value == 0, 'Deposit: ETH is not required for this operation');
May  be adding this to depositToYield internal function is more efficient

2022-01-28 07:42 UTC, KalpitaMandal commented
> Missed this check in `_repay` function from creditLines

The check is present in `repay` function which calls the `_repay` function, so the same was not iterated in the internal function. 
Let me know if it i required anyway.

2022-01-28 07:45 UTC, KalpitaMandal commented on contracts/CreditLine/CreditLine.sol
> +            require(msg.value == 0, 'DepositCollateral: ETH is not required for this operation');
The change is made but having the check in the internal function will revert only after another function is called. Putting it in the external function will ensure the internal function is never called if ETH is sent.

2022-01-28 07:54 UTC, KalpitaMandal commented on contracts/Pool/Pool.sol
> +        if(Address(poolConstants.collateralAsset) != Address(0) || _transferFromSavingsAccount) {
Added the change

2022-01-28 07:57 UTC, KalpitaMandal commented on contracts/SavingsAccount/SavingsAccount.sol
> +            require(msg.value == 0, 'Deposit: ETH is not required for this operation');
Added the change.

2022-01-31 08:23 UTC, prateekreddy requested changes
https://github.com/sublime-finance/sublime-v1/blob/CS-lime-203/contracts/SavingsAccount/SavingsAccountUtil.sol#L49 doesn't have `msg.value` check and https://github.com/sublime-finance/sublime-v1/blob/CS-lime-203/contracts/Pool/Pool.sol#L594 function doesn't need to be payable. Receive method can be removed from all contracts. RepayPrinciple in repayments.sol hasn't been covered.

2022-01-31 14:01 UTC, prateekreddy approved these changes

2022-01-31 14:22 UTC, merged