added withdrawLiquidity function
sublime-finance/sublime-v1 pull request #3
Opened 2021-03-02 09:41 UTC by aditya26026

2021-03-02 11:01 UTC, prateekreddy requested changes

2021-03-02 11:02 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        uint256 _amountwithdrawable = calculatewithdrawRepayment(lenderAddress);
It has been implemented in Pool.sol itself

2021-03-02 11:03 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        external payable
Yep. Will change this

2021-03-02 11:03 UTC, aditya26026 commented on contracts/Pool/Pool.sol
>      function withdrawLiquidity(address lenderAddress)
We plan to use withdrawRepayment

2021-03-02 11:03 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +            loanStatus == LoanStatus.CANCELLED ||
done this.

2021-03-02 11:06 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        external payable
Will change this.

2021-03-02 11:06 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        require(_balanceOfLender != 0);
done

2021-03-02 11:44 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 _amountwithdrawable = calculatewithdrawRepayment(lenderAddress);
Can we complete this function as well ?

2021-03-02 11:46 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 _amountwithdrawable = calculatewithdrawRepayment(lenderAddress);
change the  name to  calculateWithdrawRepayment

2021-03-02 11:48 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        uint256 _amountwithdrawable = calculatewithdrawRepayment(lenderAddress);
I want to finish this function along with liquidation and repayment. So, will it be okay to finish it later?

2021-03-05 02:55 UTC, prateekreddy requested changes

2021-03-05 02:55 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 _amountwithdrawable = calculatewithdrawRepayment(msg.sender);
This already takes into account amount which is withdrawn already right

2021-03-05 02:55 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        uint256 _totalSupplied = _balanceOfLender.add(_amountwithdrawable);
Variable name can probably be changed from _totalSupplied to _due ?

2021-03-05 02:55 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        IERC20(borrowAsset).transfer(
This will probably fail if the borrower withdrew tokens and then the pool was terminated. In that case, how do you handle. Do you want to add a require statement  there saying if the pool is terminated, then ask admin regarding the refunds.

2021-03-05 04:59 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        uint256 _amountwithdrawable = calculatewithdrawRepayment(msg.sender);
yep

2021-03-05 05:00 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        uint256 _totalSupplied = _balanceOfLender.add(_amountwithdrawable);
will do

2021-03-06 05:16 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        //TODO: to decide which contract will contain this
Move this to repayment contract, Pool contract is already too big

2021-03-06 05:20 UTC, merged