Get tokens for shares compound yield
sublime-finance/sublime-v1 pull request #312
Opened 2022-02-17 16:17 UTC by KalpitaMandal

The exchangeRateCurrent is multiplied by the shares and a .div(1e18) is added because the exchangeRate is raised to 1e18 decimals in compound contracts

```
uint256 exchangeRateCurrent = ICToken(cToken).exchangeRateCurrent();
uint256 expectedamount = exchangeRateCurrent.mul(shares).div(1e18);
```

2022-02-18 10:56 UTC, prateekreddy requested changes

2022-02-18 10:56 UTC, prateekreddy commented on contracts/interfaces/Invest/ICToken.sol
>      function exchangeRateStored() external view returns (uint256);
Let's remove this if not being used.

2022-02-18 10:56 UTC, prateekreddy commented on contracts/yield/CompoundYield.sol
> +        // uint256 amount = ICToken(cToken).balanceOfUnderlying(address(this)).mul(shares).div(IERC20(cToken).balanceOf(address(this)));
Cleanup comments

2022-03-01 12:32 UTC, prateekreddy requested changes

2022-03-01 12:32 UTC, prateekreddy commented on contracts/yield/CompoundYield.sol
> +        uint256 exchangeRateCurrent = ICToken(cToken).exchangeRateCurrent();
Use exchangeRateCurrent for getSharesForTokens as well

2022-03-01 12:50 UTC, KalpitaMandal commented on contracts/yield/CompoundYield.sol
> +        uint256 exchangeRateCurrent = ICToken(cToken).exchangeRateCurrent();
Added the changes

2022-03-01 12:50 UTC, KalpitaMandal commented on contracts/yield/CompoundYield.sol
> +import 'hardhat/console.sol';
Removed

2022-03-01 12:54 UTC, prateekreddy commented on contracts/yield/CompoundYield.sol
> +        return (_amount.mul(1e18)).div(exchangeRateCurrent);
.mul(1e18) no necessary

2022-03-01 12:57 UTC, merged