Changes in pooledCreditLine
sublime-finance/sublime-v1 pull request #337
Opened 2022-03-09 08:32 UTC by saxenism

1. Removed the `require` statement in the function `close` and replaced it with a pre-existing modifier
2. Added the `cancel` function in `PooledCreditLine.sol`
3. Added an event, emitted when a pooledCreditLine is cancelled
4. Removed an existing event which was supposed to be called when pooledCreditLine was `reset` (which never happens in the code base)
5. Added a function called `requestCancelled` in `LenderPool.sol` so that `creditLines` mapping for that particular `id` can be deleted too

2022-03-09 08:47 UTC, prateekreddy commented on contracts/PooledCreditLine/PooledCreditLine.sol
> +        require(creditLineVariables[_id].status == CreditLineStatus.ACTIVE, '!ACTIVE');
Error  messages  shouldn't  be changed

2022-03-09 08:47 UTC, prateekreddy commented on contracts/PooledCreditLine/PooledCreditLine.sol
> +        require(creditLineVariables[_id].status == CreditLineStatus.REQUESTED);
needs message for require

2022-03-09 08:49 UTC, prateekreddy commented on contracts/PooledCreditLine/LenderPool.sol
> +        delete creditLines[_id];
If some lender has deposited tokens for lending, how will they withdraw ?

2022-03-09 08:50 UTC, prateekreddy requested changes
Please look at above comments

2022-03-09 13:14 UTC, saxenism commented
> Please look at above comments

Resolved. Please review again.

2022-03-09 13:15 UTC, saxenism commented on contracts/PooledCreditLine/PooledCreditLine.sol
> +        require(creditLineVariables[_id].status == CreditLineStatus.REQUESTED);
added.

2022-03-09 13:15 UTC, saxenism commented on contracts/PooledCreditLine/PooledCreditLine.sol
> +        require(creditLineVariables[_id].status == CreditLineStatus.ACTIVE, '!ACTIVE');
i was forking an older version of v1-alpha. pulled the latest version and fixed this. please review again.

2022-03-09 13:20 UTC, saxenism commented on contracts/PooledCreditLine/LenderPool.sol
> +        delete creditLines[_id];
Updated.

Ok, so the approach I've followed now is:
1. `cancelRequest` is called by the borrower
2. It deletes creditLineConstants and creditLineVariables inside of PooledCreditLine.sol
3. This effectively makes the creditLineStatus as 0 (NOT_CREATED)
4. The `cancelRequest` function triggers `requestCancelled` function inside of `LenderPool`
5. The `requestCancelled` function set the `creditLines[_id].startTime as 0 (and does nothing else)
6. Now, I've added another conditional in the `withdrawLiquidity` function, so that the lenders can withdraw their liquidity in the case of credit line cancellation.

Essentially, I've opted for the lenders to withdraw their liquidity themselves instead of distributing the liquidity to all eligible lenders.

2022-03-14 04:38 UTC, prateekreddy approved these changes

2022-03-14 04:38 UTC, merged