Testing
sublime-finance/sublime-v1 pull request #39
Opened 2021-03-18 09:15 UTC by ameesha1205

Contract fixes

2021-03-18 09:31 UTC, prateekreddy requested changes

2021-03-18 09:31 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(_amount >= poolConstants.idealCollateralRatio.mul(poolConstants.borrowAmountRequested.mul(price)).div(1e8), "36");
Shouldn't this be in initialize function ? Otherwise we are adding additional restriction to depositCollateral right.

2021-03-18 09:31 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(_amount >= poolConstants.idealCollateralRatio.mul(poolConstants.borrowAmountRequested.mul(price)).div(1e8), "36");
All div should be 1e16. Because both price and idealCollateralRatio are in terms of e8

2021-03-18 09:31 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +                _borrower
This should probably be msg.sender only because borrower should not be able to use any random persons allowance na.

2021-03-18 09:31 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +                _borrower
We might have to revert probably to the older function only.

2021-03-18 09:31 UTC, prateekreddy commented on contracts/interfaces/IPool.sol
> +    function depositCollateral(address _borrower, uint256 _amount, bool _transferFromSavingsAccount) external payable;
Based on the above comments in Pool, this also needs to be updated ?

2021-03-18 09:31 UTC, prateekreddy commented on contracts/mocks/Token.sol
>          _mint(msg.sender, initialSupply);
Check if we need to initialize  ownable constructor as well

2021-03-18 09:33 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(_amount >= poolConstants.idealCollateralRatio.mul(poolConstants.borrowAmountRequested.mul(price)).div(1e8), "36");
Even more gas efficient probably is instead of multiplying with price, divide with inverse of price

2021-03-18 09:34 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        require(_amount >= poolConstants.idealCollateralRatio.mul(poolConstants.borrowAmountRequested.mul(price)).div(1e8), "36");
I was trying to fix this using 
```
function checkCollateral(uint256 _collateralAmount) internal view {
        uint256 _requiredCollateral = poolConstants.collateralRatio.mul(poolConstants.borrowAmountRequested).div(IPriceOracle(IPoolFactory(msg.sender).priceOracle()).getLatestPrice(poolConstants.collateralAsset, poolConstants.borrowAsset));
        require(_collateralAmount >= _requiredCollateral, "36");
    }
    ```

2021-03-18 12:07 UTC, ameesha1205 commented on contracts/mocks/Token.sol
>          _mint(msg.sender, initialSupply);
Not needed

2021-03-19 11:46 UTC, prateekreddy requested changes

2021-03-19 11:46 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +                _borrower
Can you update this please, so that I can merge.

2021-03-19 12:05 UTC, prateekreddy approved these changes

2021-03-19 12:06 UTC, merged