Sublime v1 loan status updates
sublime-finance/sublime-v1 pull request #5
Opened 2021-03-02 15:17 UTC by aditya26026

I have added pause() in all status updates. Not really sure if this is needed or if it could indeed cause problems.

2021-03-03 10:26 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +            _poolStatus == LoanStatus.COLLECTION || (_poolStatus == LoanStatus.ACTIVE && block.timestamp<matchCollateralRatioEndTime), "Pool::cancelOpenBorrowPool - The pool cannot be cancelled when
If the borrower matched the collateral, in that case cancel should not be possible right.

2021-03-03 10:26 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        pause();
Contract should have pauser role for that. Instead probably call the _pause() method, which is an internal function

2021-03-03 10:26 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        pause();
Contract should have pauser role for that. Instead probably call the _pause() method, which is an internal function

2021-03-03 10:26 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        internal
Who calls this function and when ?

2021-03-03 10:26 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          internal
Who will call this function and when ?

2021-03-03 11:26 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +            _poolStatus == LoanStatus.COLLECTION || (_poolStatus == LoanStatus.ACTIVE && block.timestamp<matchCollateralRatioEndTime), "Pool::cancelOpenBorrowPool - The pool cannot be cancelled when
You are right about this. So I will check if the collateral Ratio crosses the threshold when the function is called

2021-03-03 11:27 UTC, aditya26026 commented on contracts/Pool/Pool.sol
>          internal
if a loan repayment is missed, then a bot should call a function(yet to be made) which calls this function.

2021-03-03 11:28 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        internal
it should be called internally when the borrower repays the full amount. This check should be present in repayAmount.

2021-03-03 11:28 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        pause();
got it

2021-03-03 11:28 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        pause();
got it.

2021-03-03 11:38 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        internal
hmm... I am just thinking why do we need a different function for it. Can we club it with repayAmount only, or is it in a different contract.

2021-03-03 11:40 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          internal
Hmm... but it doesn't have any checks to ensure that the loan payment was really missed. Also this is an internal function

2021-03-03 11:40 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        internal
If it  is in different contract, then this function can't be external, but again  it cannot be public as well because not everyone should be  able to  call this function.

2021-03-03 11:42 UTC, prateekreddy commented
> I have added pause() in all status updates. Not really sure if this is needed or if it could indeed cause problems.

I think this is fine, when the loan is not active (for whatever reason like closed, terminated, cancelled), then there is no point in transferring lending positions to someone else. So it makes sense to pause all lending position transfers.

2021-03-03 11:49 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        internal
We can. So i will remove the function itself.

2021-03-03 11:50 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        pause();
Should _pause() be called for in case if a loan is terminated, defaulted or cancelled.

2021-03-03 11:52 UTC, aditya26026 commented on contracts/Pool/Pool.sol
>          internal
So, there has to be a function which checks if a repayment is missed and then calls this defaultLoan function.

2021-03-03 12:09 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>          internal
sure, let's add this to the liquidation function I guess.

2021-03-05 03:13 UTC, prateekreddy requested changes

2021-03-05 03:13 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +            emit LoanDefaulted();
If user has already withdrawn the collateral by the time loan is terminated, what is the course of action ?

2021-03-05 03:13 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        // TODO: check if the loan has beencompletely repayed.
Let's merge once this is complete

2021-03-05 06:57 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +            emit LoanDefaulted();
how could the user withdraw collateral if the loan is in active status

2021-03-05 09:31 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        internal
The borrower would call the function when the loan is repayed and he wants to close the loan.

2021-03-05 09:32 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        require(nextDuePeriod==0 && _totalAsset>totalSupply(), "Pool::closeLoan - The loan has not been fully repayed.");
nextDuePeriod would start out with 1 and we would set it to 0 if all interest repayments are done. I have assumed here that the principle would be transferred to the pool contract and not the repayment Contract.

2021-03-06 10:38 UTC, prateekreddy approved these changes

2021-03-06 10:38 UTC, merged