cancelling pool incurs penalty
sublime-finance/sublime-v1 pull request #59
Opened 2021-06-08 11:42 UTC by prateekreddy

2021-06-16 14:49 UTC, ritik99 commented on contracts/Pool/Pool.sol
> +            _balance = _balance.mul(poolVars.penalityLiquidityAmount).div(poolToken.totalSupply());
Shouldn't this be _balance = _balance(1 + penalityLiquidityAmount / totalSupply)?

2021-06-16 14:56 UTC, ritik99 commented on contracts/Pool/Pool.sol
>              _balance = _balance.mul(_totalAsset).div(poolToken.totalSupply());
Are we handling the case of withdrawing liquidity after lender margin called separately? Might need separate logic if lender withdrawing liquidity has margin called (and then the borrower is getting liquidated) vs when the borrower defaults by missing repayment

2021-06-17 08:08 UTC, ritik99 requested changes
Added two comments

2021-06-17 08:20 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +            _balance = _balance.mul(poolVars.penalityLiquidityAmount).div(poolToken.totalSupply());
correct, fixing it.

2021-06-17 08:28 UTC, prateekreddy commented on contracts/Pool/Pool.sol
>              _balance = _balance.mul(_totalAsset).div(poolToken.totalSupply());
When lender margin calls, liquidator directly transfers the lent tokens to lender. So the balance of the lender will be 0.

2021-06-17 12:14 UTC, ritik99 commented
Looks good!

2021-06-17 12:15 UTC, ritik99 approved these changes

2021-06-17 13:33 UTC, merged