Lending added
sublime-finance/sublime-v1 pull request #60
Opened 2021-06-09 05:12 UTC by akshay111meher

2021-06-09 05:33 UTC, prateekreddy requested changes

2021-06-09 05:33 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +import "hardhat/console.sol";
Can you remove this ?

2021-06-09 05:33 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +                    _amount
Why this change ?

2021-06-09 05:33 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +                // );
Don't comment, remove completely.

2021-06-16 11:26 UTC, akshay111meher commented on contracts/Pool/Pool.sol
> +                    _amount
liquidity shares seem to be a wrong input there. 

When consoled, _amount was making the transaction pass. 

Tried simulating with some tokens as well.

2021-06-16 11:27 UTC, akshay111meher commented on contracts/Pool/Pool.sol
> +                // );
Will resolve this once, the above comment is confirmed..

2021-06-16 12:04 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +                    _amount
Makes sense, savings account should  take actually value as input, not the liquidity shares

2021-06-16 13:44 UTC, closed without merging

2021-06-16 13:45 UTC, akshay111meher commented
The merge is redundant. 
Inclusive changes in other branch