Sublime v1 collateral ratio
sublime-finance/sublime-v1 pull request #7
Opened 2021-03-02 15:50 UTC by aditya26026

2021-03-03 11:29 UTC, prateekreddy commented
Copy the storage variable into memory, if you are going to use it multiple times.

2021-03-03 12:06 UTC, prateekreddy requested changes

2021-03-03 15:06 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +                IRepayment(Repayment).calculateRepayAmount(
This has to be done

2021-03-03 15:54 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        _ratio = (_currentCollateralTokens.mul(_ratioOfPrices)).div(
ChainLink multiplies the ratios by a factor of 10^8. So I have divided the numbers by the same

2021-03-04 11:51 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +    uint256 gracePenaltyRate;
done

2021-03-04 11:52 UTC, aditya26026 commented on contracts/Pool/Pool.sol
>      // TODO
done

2021-03-05 03:57 UTC, prateekreddy requested changes

2021-03-05 03:57 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +    uint256 public gracePeriodPenaltyFraction;
This will be part of poolFactory

2021-03-05 03:57 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        if (_interest < _extraInterest) {
Is this possible ? Does interest already include the extraInterest as well right

2021-03-05 03:57 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        address _collateralToken = collateralAsset;
If both use similar code, then can you seperate the common code into a different internal function

2021-03-05 03:57 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        address _collateralToken = collateralAsset;
I mean getCurrentCollateralRatio

2021-03-05 05:23 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        address _collateralToken = collateralAsset;
will do

2021-03-05 05:26 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +        if (_interest < _extraInterest) {
Say he has to pay 100 dai in 8 days. The borrower has already paid 60 dai for an interval. The _interest left to be paid would be 40 dai for that interval. On the 4th day, the _extraInterest would be 50 dai. So in that case the borrower does not owe money to the pool.

2021-03-05 05:28 UTC, aditya26026 commented on contracts/Pool/Pool.sol
> +    uint256 public gracePeriodPenaltyFraction;
The problem with having this as a global variable is that changing this during the execution of a pool would mess up all the calculations for liquidation and repayments.

2021-03-05 07:54 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +    uint256 public gracePeriodPenaltyFraction;
ok sure, will intialize the pool with the value, in that case

2021-03-05 07:57 UTC, prateekreddy commented on contracts/Pool/Pool.sol
> +        if (_interest < _extraInterest) {
cool, makes sense.

2021-03-05 08:25 UTC, prateekreddy approved these changes

2021-03-05 08:36 UTC, merged