Natspec comments
sublime-finance/sublime-v1 pull request #79
Opened 2021-07-08 13:37 UTC by ritik99

2021-07-09 09:09 UTC, prateekreddy requested changes

2021-07-09 09:09 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +     * @param _amount amount of liquidity shares to withdraw
This is the base token amount, we don't use liquidity shares anymore as input to savings account

2021-07-09 09:09 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +     * @param _amount amount of **liquidity shares** to be reinvested
We use only base token amount as input

2021-07-09 09:09 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +    * @param _amount amount to be withdrawn
Let's probably specify that this is base token amount

2021-07-09 09:09 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
> +    * @param _amount amount to be withdrawn
Let's probably specify that this is base token amount

2021-07-09 09:09 UTC, prateekreddy commented on contracts/SavingsAccount/SavingsAccount.sol
>          address from,
Let's add _ to other params as well

2021-07-09 11:00 UTC, ritik99 commented on contracts/SavingsAccount/SavingsAccount.sol
> +    * @param to address of the savings account owner
savings account holder?

2021-11-08 06:26 UTC, prateekreddy commented
Naspec docs completed as a separate task. Closing as this is not needed anymore.

2021-11-08 06:26 UTC, closed without merging