Fix/repayments
sublime-finance/sublime-v1 pull request #80
Opened 2021-07-14 05:12 UTC by prateekreddy

Repay functions fixed

2021-07-14 07:05 UTC, ritik99 requested changes

2021-07-14 07:05 UTC, ritik99 commented on contracts/Repayments/Repayments.sol
> +        _amount = _amount * 10**30;
does this pass with all the other tests?

2021-07-14 07:07 UTC, prateekreddy commented on contracts/Repayments/Repayments.sol
> +                    ).div(10**30)
right... will fix.

2021-07-14 07:08 UTC, prateekreddy commented on contracts/Repayments/Repayments.sol
> +        _amount = _amount * 10**30;
yeah it does

2021-07-14 07:22 UTC, ritik99 approved these changes

2021-07-19 06:17 UTC, ritik99 approved these changes

2021-07-19 06:18 UTC, merged