Natspec comments for the `Repayments` module
sublime-finance/sublime-v1 pull request #85
Opened 2021-07-29 20:32 UTC by saxenism

Even though natspec comments are not required for functions that are not public or external, I've still made those for better understanding.

2021-08-17 10:34 UTC, ritik99 approved these changes

2021-09-02 10:18 UTC, prateekreddy requested changes

2021-09-02 10:18 UTC, prateekreddy commented on contracts/Repayments/Repayments.sol
> +    address PoolFactory;
This doesn't seem to exist on the master branch, can you please check ?

2021-09-02 10:35 UTC, saxenism commented on contracts/Repayments/Repayments.sol
> +    address PoolFactory;
Yes, correct. Removed it.

2021-09-02 10:58 UTC, prateekreddy approved these changes

2021-09-02 10:58 UTC, merged